#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan  7 18:52:41 2019

@author: arnikavishwakarma
"""

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
"""
s = "abcd"
t = "abcde"
s_sorted = sorted(s)
t_sorted = sorted(t)

for i in range(len(t_sorted))[::-1]:
    print(i)
    if t_sorted[i] in s_sorted:
        s_sorted.pop()
        t_sorted.pop()
    else:
        print( t_sorted[-1])