#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan  9 14:42:22 2019

@author: arnikavishwakarma
"""

def triplet(arr,n):
    #found = []
    for i in range(0,n-2):
        for j in range(i+1,n-1):
            for k in range(j+1, n):
                if arr[i] + arr[j] + arr[k] == 0:
                    return [arr[i], arr[j], arr[k]]
                    
    return []             
                    
arr =[0,-1,2,-3,1]
n = len(arr)
print(triplet(arr,n))